/**
 * Base de alimentos comunes con valores nutricionales por 100g.
 * Fuente: USDA FoodData Central / FAO / Tablas de composición de alimentos de México (INNSZ).
 */

export interface AlimentoComun {
  nombre: string
  categoria: string
  calorias: number
  proteina_g: number
  carbohidratos_g: number
  grasas_g: number
  grasas_saturadas_g: number
  fibra_g: number
  sodio_mg: number
  azucar_g: number
  colesterol_mg: number
  calcio_mg: number
  hierro_mg: number
  vitamina_c_mg: number
  vitamina_d_ug: number
  /** Gramos de una porción típica (para mostrar referencia al usuario) */
  porcion_tipica_g?: number
  /** Etiqueta de la porción típica, ej: "1 huevo", "1 vaso (200 ml)" */
  porcion_label?: string
  /** Peso de 1 unidad individual en gramos (ej: 1 fresa ≈ 12g).
   *  Se usa como gramos_por_unidad en modo "cantidad".
   *  Solo presente cuando 1 pieza ≠ porción típica. */
  gramos_por_unidad?: number
}

export const ALIMENTOS_COMUNES: AlimentoComun[] = [

  // ─── Huevos ────────────────────────────────────────────────────────────────
  { nombre: 'Huevo entero cocido', categoria: 'Huevos', porcion_tipica_g: 55, porcion_label: '1 huevo',
    calorias: 155, proteina_g: 13, carbohidratos_g: 1.1, grasas_g: 11, grasas_saturadas_g: 3.3,
    fibra_g: 0, sodio_mg: 124, azucar_g: 1.1, colesterol_mg: 373, calcio_mg: 56, hierro_mg: 1.9, vitamina_c_mg: 0, vitamina_d_ug: 2 },
  { nombre: 'Huevo entero revuelto', categoria: 'Huevos', porcion_tipica_g: 55, porcion_label: '1 huevo',
    calorias: 149, proteina_g: 10, carbohidratos_g: 1.6, grasas_g: 11, grasas_saturadas_g: 3.3,
    fibra_g: 0, sodio_mg: 171, azucar_g: 1.4, colesterol_mg: 352, calcio_mg: 57, hierro_mg: 1.6, vitamina_c_mg: 0, vitamina_d_ug: 1.7 },
  { nombre: 'Clara de huevo', categoria: 'Huevos', porcion_tipica_g: 33, porcion_label: '1 clara',
    calorias: 52, proteina_g: 11, carbohidratos_g: 0.7, grasas_g: 0.2, grasas_saturadas_g: 0,
    fibra_g: 0, sodio_mg: 166, azucar_g: 0.7, colesterol_mg: 0, calcio_mg: 7, hierro_mg: 0.1, vitamina_c_mg: 0, vitamina_d_ug: 0 },
  { nombre: 'Yema de huevo', categoria: 'Huevos', porcion_tipica_g: 17, porcion_label: '1 yema',
    calorias: 322, proteina_g: 16, carbohidratos_g: 3.6, grasas_g: 27, grasas_saturadas_g: 8.3,
    fibra_g: 0, sodio_mg: 48, azucar_g: 0.6, colesterol_mg: 1234, calcio_mg: 129, hierro_mg: 2.7, vitamina_c_mg: 0, vitamina_d_ug: 5.4 },

  // ─── Lácteos ───────────────────────────────────────────────────────────────
  { nombre: 'Leche entera', categoria: 'Lácteos', porcion_tipica_g: 200, porcion_label: '1 vaso (200 ml)',
    calorias: 61, proteina_g: 3.2, carbohidratos_g: 4.8, grasas_g: 3.3, grasas_saturadas_g: 1.9,
    fibra_g: 0, sodio_mg: 44, azucar_g: 4.8, colesterol_mg: 10, calcio_mg: 113, hierro_mg: 0.1, vitamina_c_mg: 0, vitamina_d_ug: 1.2 },
  { nombre: 'Leche descremada', categoria: 'Lácteos', porcion_tipica_g: 200, porcion_label: '1 vaso (200 ml)',
    calorias: 34, proteina_g: 3.4, carbohidratos_g: 5, grasas_g: 0.1, grasas_saturadas_g: 0.1,
    fibra_g: 0, sodio_mg: 44, azucar_g: 5, colesterol_mg: 2, calcio_mg: 122, hierro_mg: 0.1, vitamina_c_mg: 0, vitamina_d_ug: 1.2 },
  { nombre: 'Leche semidescremada', categoria: 'Lácteos', porcion_tipica_g: 200, porcion_label: '1 vaso (200 ml)',
    calorias: 46, proteina_g: 3.3, carbohidratos_g: 4.8, grasas_g: 1.6, grasas_saturadas_g: 1,
    fibra_g: 0, sodio_mg: 44, azucar_g: 4.8, colesterol_mg: 5, calcio_mg: 116, hierro_mg: 0.1, vitamina_c_mg: 0, vitamina_d_ug: 1.2 },
  { nombre: 'Yogur natural', categoria: 'Lácteos', porcion_tipica_g: 245, porcion_label: '1 taza',
    calorias: 59, proteina_g: 3.5, carbohidratos_g: 5, grasas_g: 3.3, grasas_saturadas_g: 2.1,
    fibra_g: 0, sodio_mg: 36, azucar_g: 5, colesterol_mg: 13, calcio_mg: 121, hierro_mg: 0.1, vitamina_c_mg: 0.5, vitamina_d_ug: 0 },
  { nombre: 'Yogur griego natural', categoria: 'Lácteos', porcion_tipica_g: 245, porcion_label: '1 taza',
    calorias: 73, proteina_g: 9, carbohidratos_g: 3.6, grasas_g: 2.5, grasas_saturadas_g: 1.6,
    fibra_g: 0, sodio_mg: 36, azucar_g: 3.6, colesterol_mg: 8, calcio_mg: 100, hierro_mg: 0.1, vitamina_c_mg: 0, vitamina_d_ug: 0 },
  { nombre: 'Queso panela', categoria: 'Lácteos', porcion_tipica_g: 30, porcion_label: '1 rebanada',
    calorias: 290, proteina_g: 20, carbohidratos_g: 3, grasas_g: 22, grasas_saturadas_g: 14,
    fibra_g: 0, sodio_mg: 600, azucar_g: 0.5, colesterol_mg: 75, calcio_mg: 600, hierro_mg: 0.2, vitamina_c_mg: 0, vitamina_d_ug: 0.5 },
  { nombre: 'Queso Oaxaca', categoria: 'Lácteos', porcion_tipica_g: 30, porcion_label: '30 g (hebra)',
    calorias: 356, proteina_g: 23, carbohidratos_g: 2, grasas_g: 28, grasas_saturadas_g: 18,
    fibra_g: 0, sodio_mg: 700, azucar_g: 0, colesterol_mg: 90, calcio_mg: 700, hierro_mg: 0.3, vitamina_c_mg: 0, vitamina_d_ug: 0.5 },
  { nombre: 'Queso cheddar', categoria: 'Lácteos', porcion_tipica_g: 28, porcion_label: '1 rebanada',
    calorias: 403, proteina_g: 25, carbohidratos_g: 1.3, grasas_g: 33, grasas_saturadas_g: 21,
    fibra_g: 0, sodio_mg: 621, azucar_g: 0.5, colesterol_mg: 105, calcio_mg: 721, hierro_mg: 0.7, vitamina_c_mg: 0, vitamina_d_ug: 0.6 },
  { nombre: 'Queso cottage', categoria: 'Lácteos', porcion_tipica_g: 120, porcion_label: '½ taza',
    calorias: 98, proteina_g: 11, carbohidratos_g: 3.4, grasas_g: 4.3, grasas_saturadas_g: 1.7,
    fibra_g: 0, sodio_mg: 364, azucar_g: 2.7, colesterol_mg: 17, calcio_mg: 83, hierro_mg: 0.2, vitamina_c_mg: 0, vitamina_d_ug: 0 },
  { nombre: 'Crema ácida', categoria: 'Lácteos', porcion_tipica_g: 15, porcion_label: '1 cda',
    calorias: 193, proteina_g: 2.1, carbohidratos_g: 4.6, grasas_g: 19, grasas_saturadas_g: 12,
    fibra_g: 0, sodio_mg: 53, azucar_g: 3.8, colesterol_mg: 50, calcio_mg: 116, hierro_mg: 0.1, vitamina_c_mg: 0.5, vitamina_d_ug: 0.2 },
  { nombre: 'Mantequilla', categoria: 'Lácteos', porcion_tipica_g: 14, porcion_label: '1 cda',
    calorias: 717, proteina_g: 0.9, carbohidratos_g: 0.1, grasas_g: 81, grasas_saturadas_g: 51,
    fibra_g: 0, sodio_mg: 643, azucar_g: 0.1, colesterol_mg: 215, calcio_mg: 24, hierro_mg: 0, vitamina_c_mg: 0, vitamina_d_ug: 1.5 },

  // ─── Carnes de res y cerdo ─────────────────────────────────────────────────
  { nombre: 'Bistec de res', categoria: 'Carnes', porcion_tipica_g: 120, porcion_label: '1 bistec',
    calorias: 217, proteina_g: 26, carbohidratos_g: 0, grasas_g: 12, grasas_saturadas_g: 4.5,
    fibra_g: 0, sodio_mg: 66, azucar_g: 0, colesterol_mg: 80, calcio_mg: 11, hierro_mg: 2.6, vitamina_c_mg: 0, vitamina_d_ug: 0.1 },
  { nombre: 'Carne molida de res', categoria: 'Carnes', porcion_tipica_g: 100, porcion_label: '1 porción (100 g)',
    calorias: 176, proteina_g: 20, carbohidratos_g: 0, grasas_g: 10, grasas_saturadas_g: 4,
    fibra_g: 0, sodio_mg: 75, azucar_g: 0, colesterol_mg: 65, calcio_mg: 18, hierro_mg: 2.5, vitamina_c_mg: 0, vitamina_d_ug: 0.1 },
  { nombre: 'Filete de res', categoria: 'Carnes', porcion_tipica_g: 120, porcion_label: '1 filete',
    calorias: 271, proteina_g: 24, carbohidratos_g: 0, grasas_g: 19, grasas_saturadas_g: 7.5,
    fibra_g: 0, sodio_mg: 59, azucar_g: 0, colesterol_mg: 82, calcio_mg: 9, hierro_mg: 2.3, vitamina_c_mg: 0, vitamina_d_ug: 0.1 },
  { nombre: 'Lomo de cerdo', categoria: 'Carnes', porcion_tipica_g: 100, porcion_label: '1 porción (100 g)',
    calorias: 190, proteina_g: 27, carbohidratos_g: 0, grasas_g: 9, grasas_saturadas_g: 3,
    fibra_g: 0, sodio_mg: 62, azucar_g: 0, colesterol_mg: 80, calcio_mg: 19, hierro_mg: 1, vitamina_c_mg: 0, vitamina_d_ug: 0.5 },
  { nombre: 'Costilla de cerdo', categoria: 'Carnes', porcion_tipica_g: 80, porcion_label: '1 costilla',
    calorias: 278, proteina_g: 18, carbohidratos_g: 0, grasas_g: 23, grasas_saturadas_g: 8.5,
    fibra_g: 0, sodio_mg: 68, azucar_g: 0, colesterol_mg: 80, calcio_mg: 16, hierro_mg: 0.9, vitamina_c_mg: 0, vitamina_d_ug: 0.4 },
  { nombre: 'Jamón de pavo', categoria: 'Carnes', porcion_tipica_g: 30, porcion_label: '1 rebanada',
    calorias: 107, proteina_g: 14, carbohidratos_g: 3.5, grasas_g: 4, grasas_saturadas_g: 1.3,
    fibra_g: 0, sodio_mg: 925, azucar_g: 1.8, colesterol_mg: 50, calcio_mg: 8, hierro_mg: 1.1, vitamina_c_mg: 0, vitamina_d_ug: 0.1 },
  { nombre: 'Tocino de cerdo', categoria: 'Carnes', porcion_tipica_g: 12, porcion_label: '1 tira',
    calorias: 541, proteina_g: 37, carbohidratos_g: 1.4, grasas_g: 42, grasas_saturadas_g: 14,
    fibra_g: 0, sodio_mg: 1717, azucar_g: 0, colesterol_mg: 110, calcio_mg: 9, hierro_mg: 1, vitamina_c_mg: 0, vitamina_d_ug: 1.1 },
  { nombre: 'Salchicha de pavo', categoria: 'Carnes', porcion_tipica_g: 50, porcion_label: '1 pieza',
    calorias: 218, proteina_g: 13, carbohidratos_g: 3, grasas_g: 17, grasas_saturadas_g: 4.8,
    fibra_g: 0, sodio_mg: 760, azucar_g: 1, colesterol_mg: 75, calcio_mg: 17, hierro_mg: 0.9, vitamina_c_mg: 0, vitamina_d_ug: 0.1 },

  // ─── Aves ──────────────────────────────────────────────────────────────────
  { nombre: 'Pechuga de pollo cocida', categoria: 'Aves', porcion_tipica_g: 120, porcion_label: '1 pechuga',
    calorias: 165, proteina_g: 31, carbohidratos_g: 0, grasas_g: 3.6, grasas_saturadas_g: 1,
    fibra_g: 0, sodio_mg: 74, azucar_g: 0, colesterol_mg: 85, calcio_mg: 11, hierro_mg: 1, vitamina_c_mg: 0, vitamina_d_ug: 0.1 },
  { nombre: 'Muslo de pollo cocido', categoria: 'Aves', porcion_tipica_g: 100, porcion_label: '1 muslo',
    calorias: 209, proteina_g: 26, carbohidratos_g: 0, grasas_g: 11, grasas_saturadas_g: 3,
    fibra_g: 0, sodio_mg: 84, azucar_g: 0, colesterol_mg: 93, calcio_mg: 12, hierro_mg: 1.3, vitamina_c_mg: 0, vitamina_d_ug: 0.1 },
  { nombre: 'Pollo entero asado', categoria: 'Aves', porcion_tipica_g: 100, porcion_label: '1 porción (100 g)',
    calorias: 239, proteina_g: 27, carbohidratos_g: 0, grasas_g: 14, grasas_saturadas_g: 3.8,
    fibra_g: 0, sodio_mg: 82, azucar_g: 0, colesterol_mg: 88, calcio_mg: 13, hierro_mg: 1.3, vitamina_c_mg: 0, vitamina_d_ug: 0.1 },
  { nombre: 'Pechuga de pavo cocida', categoria: 'Aves', porcion_tipica_g: 100, porcion_label: '1 porción (100 g)',
    calorias: 135, proteina_g: 30, carbohidratos_g: 0, grasas_g: 1, grasas_saturadas_g: 0.3,
    fibra_g: 0, sodio_mg: 63, azucar_g: 0, colesterol_mg: 76, calcio_mg: 12, hierro_mg: 1.4, vitamina_c_mg: 0, vitamina_d_ug: 0.1 },

  // ─── Pescados y mariscos ───────────────────────────────────────────────────
  { nombre: 'Atún en agua (escurrido)', categoria: 'Pescados', porcion_tipica_g: 140, porcion_label: '1 lata (140 g)',
    calorias: 116, proteina_g: 26, carbohidratos_g: 0, grasas_g: 1, grasas_saturadas_g: 0.3,
    fibra_g: 0, sodio_mg: 320, azucar_g: 0, colesterol_mg: 42, calcio_mg: 11, hierro_mg: 1.3, vitamina_c_mg: 0, vitamina_d_ug: 3.8 },
  { nombre: 'Salmón cocido', categoria: 'Pescados', porcion_tipica_g: 120, porcion_label: '1 porción (120 g)',
    calorias: 208, proteina_g: 20, carbohidratos_g: 0, grasas_g: 13, grasas_saturadas_g: 3,
    fibra_g: 0, sodio_mg: 59, azucar_g: 0, colesterol_mg: 63, calcio_mg: 12, hierro_mg: 0.8, vitamina_c_mg: 3.9, vitamina_d_ug: 14.5 },
  { nombre: 'Tilapia cocida', categoria: 'Pescados', porcion_tipica_g: 130, porcion_label: '1 filete',
    calorias: 128, proteina_g: 26, carbohidratos_g: 0, grasas_g: 2.7, grasas_saturadas_g: 0.9,
    fibra_g: 0, sodio_mg: 56, azucar_g: 0, colesterol_mg: 57, calcio_mg: 14, hierro_mg: 0.6, vitamina_c_mg: 0, vitamina_d_ug: 3.1 },
  { nombre: 'Camarón cocido', categoria: 'Pescados', porcion_tipica_g: 85, porcion_label: '1 porción (85 g)',
    calorias: 99, proteina_g: 24, carbohidratos_g: 0.2, grasas_g: 0.3, grasas_saturadas_g: 0.1,
    fibra_g: 0, sodio_mg: 111, azucar_g: 0, colesterol_mg: 189, calcio_mg: 64, hierro_mg: 0.5, vitamina_c_mg: 1.9, vitamina_d_ug: 0.3 },
  { nombre: 'Sardina en lata', categoria: 'Pescados', porcion_tipica_g: 90, porcion_label: '1 lata (90 g)',
    calorias: 208, proteina_g: 25, carbohidratos_g: 0, grasas_g: 11, grasas_saturadas_g: 1.5,
    fibra_g: 0, sodio_mg: 505, azucar_g: 0, colesterol_mg: 142, calcio_mg: 382, hierro_mg: 2.9, vitamina_c_mg: 0, vitamina_d_ug: 4.8 },

  // ─── Cereales y arroz ──────────────────────────────────────────────────────
  { nombre: 'Arroz blanco cocido', categoria: 'Cereales y granos', porcion_tipica_g: 93, porcion_label: '½ taza cocida',
    calorias: 130, proteina_g: 2.7, carbohidratos_g: 28, grasas_g: 0.3, grasas_saturadas_g: 0.1,
    fibra_g: 0.4, sodio_mg: 1, azucar_g: 0, colesterol_mg: 0, calcio_mg: 10, hierro_mg: 0.2, vitamina_c_mg: 0, vitamina_d_ug: 0 },
  { nombre: 'Arroz integral cocido', categoria: 'Cereales y granos', porcion_tipica_g: 98, porcion_label: '½ taza cocida',
    calorias: 111, proteina_g: 2.6, carbohidratos_g: 23, grasas_g: 0.9, grasas_saturadas_g: 0.2,
    fibra_g: 1.8, sodio_mg: 5, azucar_g: 0.4, colesterol_mg: 0, calcio_mg: 10, hierro_mg: 0.5, vitamina_c_mg: 0, vitamina_d_ug: 0 },
  { nombre: 'Avena en hojuelas', categoria: 'Cereales y granos', porcion_tipica_g: 40, porcion_label: '½ taza (seca)',
    calorias: 389, proteina_g: 17, carbohidratos_g: 66, grasas_g: 7, grasas_saturadas_g: 1.2,
    fibra_g: 10.6, sodio_mg: 2, azucar_g: 1, colesterol_mg: 0, calcio_mg: 54, hierro_mg: 4.7, vitamina_c_mg: 0, vitamina_d_ug: 0 },
  { nombre: 'Avena cocida con agua', categoria: 'Cereales y granos', porcion_tipica_g: 240, porcion_label: '1 taza cocida',
    calorias: 71, proteina_g: 2.5, carbohidratos_g: 12, grasas_g: 1.5, grasas_saturadas_g: 0.3,
    fibra_g: 1.7, sodio_mg: 49, azucar_g: 0.3, colesterol_mg: 0, calcio_mg: 11, hierro_mg: 0.7, vitamina_c_mg: 0, vitamina_d_ug: 0 },
  { nombre: 'Pasta cocida (espagueti)', categoria: 'Cereales y granos', porcion_tipica_g: 140, porcion_label: '1 taza cocida',
    calorias: 131, proteina_g: 5, carbohidratos_g: 25, grasas_g: 1.1, grasas_saturadas_g: 0.2,
    fibra_g: 1.8, sodio_mg: 1, azucar_g: 0.6, colesterol_mg: 0, calcio_mg: 7, hierro_mg: 1.3, vitamina_c_mg: 0, vitamina_d_ug: 0 },
  { nombre: 'Pasta integral cocida', categoria: 'Cereales y granos', porcion_tipica_g: 140, porcion_label: '1 taza cocida',
    calorias: 124, proteina_g: 5.3, carbohidratos_g: 23, grasas_g: 1, grasas_saturadas_g: 0.2,
    fibra_g: 3.2, sodio_mg: 3, azucar_g: 0.8, colesterol_mg: 0, calcio_mg: 17, hierro_mg: 1.6, vitamina_c_mg: 0, vitamina_d_ug: 0 },
  { nombre: 'Quinoa cocida', categoria: 'Cereales y granos', porcion_tipica_g: 93, porcion_label: '½ taza cocida',
    calorias: 120, proteina_g: 4.4, carbohidratos_g: 22, grasas_g: 1.9, grasas_saturadas_g: 0.2,
    fibra_g: 2.8, sodio_mg: 7, azucar_g: 0.9, colesterol_mg: 0, calcio_mg: 17, hierro_mg: 1.5, vitamina_c_mg: 0, vitamina_d_ug: 0 },
  { nombre: 'Maíz dulce cocido', categoria: 'Cereales y granos', porcion_tipica_g: 82, porcion_label: '½ taza',
    calorias: 96, proteina_g: 3.4, carbohidratos_g: 21, grasas_g: 1.5, grasas_saturadas_g: 0.2,
    fibra_g: 2.4, sodio_mg: 15, azucar_g: 4.5, colesterol_mg: 0, calcio_mg: 2, hierro_mg: 0.5, vitamina_c_mg: 6.8, vitamina_d_ug: 0 },
  { nombre: 'Granola (sin azúcar añadida)', categoria: 'Cereales y granos', porcion_tipica_g: 30, porcion_label: '¼ taza',
    calorias: 471, proteina_g: 10, carbohidratos_g: 64, grasas_g: 21, grasas_saturadas_g: 3.5,
    fibra_g: 7, sodio_mg: 26, azucar_g: 18, colesterol_mg: 0, calcio_mg: 53, hierro_mg: 3.4, vitamina_c_mg: 0.4, vitamina_d_ug: 0 },

  // ─── Panes y tortillas ─────────────────────────────────────────────────────
  { nombre: 'Tortilla de maíz', categoria: 'Panes y tortillas', porcion_tipica_g: 30, porcion_label: '1 tortilla',
    calorias: 218, proteina_g: 5.7, carbohidratos_g: 46, grasas_g: 2.5, grasas_saturadas_g: 0.3,
    fibra_g: 6.5, sodio_mg: 11, azucar_g: 0.7, colesterol_mg: 0, calcio_mg: 114, hierro_mg: 2.3, vitamina_c_mg: 0, vitamina_d_ug: 0 },
  { nombre: 'Tortilla de harina', categoria: 'Panes y tortillas', porcion_tipica_g: 45, porcion_label: '1 tortilla',
    calorias: 312, proteina_g: 8.3, carbohidratos_g: 52, grasas_g: 7.5, grasas_saturadas_g: 2.8,
    fibra_g: 2.5, sodio_mg: 592, azucar_g: 2.2, colesterol_mg: 0, calcio_mg: 91, hierro_mg: 3.2, vitamina_c_mg: 0, vitamina_d_ug: 0 },
  { nombre: 'Pan blanco (bimbo)', categoria: 'Panes y tortillas', porcion_tipica_g: 25, porcion_label: '1 rebanada',
    calorias: 265, proteina_g: 9, carbohidratos_g: 49, grasas_g: 3.2, grasas_saturadas_g: 0.7,
    fibra_g: 2.7, sodio_mg: 491, azucar_g: 5, colesterol_mg: 0, calcio_mg: 151, hierro_mg: 3.6, vitamina_c_mg: 0, vitamina_d_ug: 0 },
  { nombre: 'Pan integral', categoria: 'Panes y tortillas', porcion_tipica_g: 28, porcion_label: '1 rebanada',
    calorias: 247, proteina_g: 13, carbohidratos_g: 41, grasas_g: 4.2, grasas_saturadas_g: 0.9,
    fibra_g: 7, sodio_mg: 472, azucar_g: 6, colesterol_mg: 0, calcio_mg: 107, hierro_mg: 3, vitamina_c_mg: 0, vitamina_d_ug: 0 },
  { nombre: 'Pan de centeno', categoria: 'Panes y tortillas', porcion_tipica_g: 28, porcion_label: '1 rebanada',
    calorias: 259, proteina_g: 8.5, carbohidratos_g: 48, grasas_g: 3.3, grasas_saturadas_g: 0.4,
    fibra_g: 5.8, sodio_mg: 603, azucar_g: 3.9, colesterol_mg: 0, calcio_mg: 73, hierro_mg: 2.8, vitamina_c_mg: 0, vitamina_d_ug: 0 },
  { nombre: 'Bolillo', categoria: 'Panes y tortillas', porcion_tipica_g: 70, porcion_label: '1 pieza',
    calorias: 272, proteina_g: 9.4, carbohidratos_g: 55, grasas_g: 1.7, grasas_saturadas_g: 0.4,
    fibra_g: 2.3, sodio_mg: 536, azucar_g: 3, colesterol_mg: 0, calcio_mg: 58, hierro_mg: 3, vitamina_c_mg: 0, vitamina_d_ug: 0 },
  { nombre: 'Tostada de maíz', categoria: 'Panes y tortillas', porcion_tipica_g: 10, porcion_label: '1 pieza',
    calorias: 393, proteina_g: 8.5, carbohidratos_g: 79, grasas_g: 5.7, grasas_saturadas_g: 0.8,
    fibra_g: 6.7, sodio_mg: 340, azucar_g: 1.5, colesterol_mg: 0, calcio_mg: 80, hierro_mg: 3.5, vitamina_c_mg: 0, vitamina_d_ug: 0 },
  { nombre: 'Galletas de avena', categoria: 'Panes y tortillas', porcion_tipica_g: 15, porcion_label: '1 galleta',
    calorias: 446, proteina_g: 7, carbohidratos_g: 67, grasas_g: 17, grasas_saturadas_g: 4.5,
    fibra_g: 3.5, sodio_mg: 327, azucar_g: 28, colesterol_mg: 0, calcio_mg: 30, hierro_mg: 2.5, vitamina_c_mg: 0, vitamina_d_ug: 0 },
  { nombre: 'Galletas saladas (crackers)', categoria: 'Panes y tortillas', porcion_tipica_g: 15, porcion_label: '5 piezas',
    calorias: 421, proteina_g: 9.5, carbohidratos_g: 70, grasas_g: 11, grasas_saturadas_g: 3,
    fibra_g: 3.3, sodio_mg: 784, azucar_g: 4, colesterol_mg: 0, calcio_mg: 33, hierro_mg: 3.3, vitamina_c_mg: 0, vitamina_d_ug: 0 },

  // ─── Leguminosas ───────────────────────────────────────────────────────────
  { nombre: 'Frijoles negros cocidos', categoria: 'Leguminosas', porcion_tipica_g: 86, porcion_label: '½ taza',
    calorias: 132, proteina_g: 8.9, carbohidratos_g: 24, grasas_g: 0.5, grasas_saturadas_g: 0.1,
    fibra_g: 8.7, sodio_mg: 1, azucar_g: 0.3, colesterol_mg: 0, calcio_mg: 27, hierro_mg: 2.1, vitamina_c_mg: 0, vitamina_d_ug: 0 },
  { nombre: 'Frijoles bayos cocidos', categoria: 'Leguminosas', porcion_tipica_g: 86, porcion_label: '½ taza',
    calorias: 127, proteina_g: 8.7, carbohidratos_g: 23, grasas_g: 0.5, grasas_saturadas_g: 0.1,
    fibra_g: 7.4, sodio_mg: 2, azucar_g: 0.3, colesterol_mg: 0, calcio_mg: 50, hierro_mg: 2.2, vitamina_c_mg: 1.2, vitamina_d_ug: 0 },
  { nombre: 'Frijoles refritos (con aceite)', categoria: 'Leguminosas', porcion_tipica_g: 50, porcion_label: '2 cdas',
    calorias: 157, proteina_g: 8.6, carbohidratos_g: 21, grasas_g: 4.5, grasas_saturadas_g: 1.6,
    fibra_g: 6.7, sodio_mg: 398, azucar_g: 0.3, colesterol_mg: 7, calcio_mg: 60, hierro_mg: 2.2, vitamina_c_mg: 0, vitamina_d_ug: 0 },
  { nombre: 'Lentejas cocidas', categoria: 'Leguminosas', porcion_tipica_g: 99, porcion_label: '½ taza',
    calorias: 116, proteina_g: 9, carbohidratos_g: 20, grasas_g: 0.4, grasas_saturadas_g: 0.1,
    fibra_g: 7.9, sodio_mg: 2, azucar_g: 1.8, colesterol_mg: 0, calcio_mg: 19, hierro_mg: 3.3, vitamina_c_mg: 1.5, vitamina_d_ug: 0 },
  { nombre: 'Garbanzos cocidos', categoria: 'Leguminosas', porcion_tipica_g: 82, porcion_label: '½ taza',
    calorias: 164, proteina_g: 8.9, carbohidratos_g: 27, grasas_g: 2.6, grasas_saturadas_g: 0.3,
    fibra_g: 7.6, sodio_mg: 7, azucar_g: 4.8, colesterol_mg: 0, calcio_mg: 49, hierro_mg: 2.9, vitamina_c_mg: 1.3, vitamina_d_ug: 0 },
  { nombre: 'Habas cocidas', categoria: 'Leguminosas', porcion_tipica_g: 85, porcion_label: '½ taza',
    calorias: 110, proteina_g: 7.6, carbohidratos_g: 20, grasas_g: 0.4, grasas_saturadas_g: 0.1,
    fibra_g: 5.4, sodio_mg: 5, azucar_g: 4.5, colesterol_mg: 0, calcio_mg: 36, hierro_mg: 1.5, vitamina_c_mg: 1.4, vitamina_d_ug: 0 },
  { nombre: 'Edamame (soya verde cocida)', categoria: 'Leguminosas', porcion_tipica_g: 80, porcion_label: '½ taza',
    calorias: 121, proteina_g: 11, carbohidratos_g: 8.9, grasas_g: 5.2, grasas_saturadas_g: 0.6,
    fibra_g: 5.2, sodio_mg: 6, azucar_g: 2.2, colesterol_mg: 0, calcio_mg: 60, hierro_mg: 2.3, vitamina_c_mg: 6.1, vitamina_d_ug: 0 },

  // ─── Verduras ──────────────────────────────────────────────────────────────
  { nombre: 'Brócoli cocido', categoria: 'Verduras', porcion_tipica_g: 91, porcion_label: '1 taza',
    calorias: 35, proteina_g: 2.4, carbohidratos_g: 7.2, grasas_g: 0.4, grasas_saturadas_g: 0,
    fibra_g: 3.3, sodio_mg: 41, azucar_g: 1.7, colesterol_mg: 0, calcio_mg: 40, hierro_mg: 0.7, vitamina_c_mg: 65, vitamina_d_ug: 0 },
  { nombre: 'Espinaca cruda', categoria: 'Verduras', porcion_tipica_g: 30, porcion_label: '1 taza',
    calorias: 23, proteina_g: 2.9, carbohidratos_g: 3.6, grasas_g: 0.4, grasas_saturadas_g: 0.1,
    fibra_g: 2.2, sodio_mg: 79, azucar_g: 0.4, colesterol_mg: 0, calcio_mg: 99, hierro_mg: 2.7, vitamina_c_mg: 28, vitamina_d_ug: 0 },
  { nombre: 'Zanahoria cruda', categoria: 'Verduras', porcion_tipica_g: 61, porcion_label: '1 zanahoria',
    calorias: 41, proteina_g: 0.9, carbohidratos_g: 10, grasas_g: 0.2, grasas_saturadas_g: 0,
    fibra_g: 2.8, sodio_mg: 69, azucar_g: 4.7, colesterol_mg: 0, calcio_mg: 33, hierro_mg: 0.3, vitamina_c_mg: 5.9, vitamina_d_ug: 0 },
  { nombre: 'Tomate rojo', categoria: 'Verduras', porcion_tipica_g: 90, porcion_label: '1 tomate',
    calorias: 18, proteina_g: 0.9, carbohidratos_g: 3.9, grasas_g: 0.2, grasas_saturadas_g: 0,
    fibra_g: 1.2, sodio_mg: 5, azucar_g: 2.6, colesterol_mg: 0, calcio_mg: 10, hierro_mg: 0.3, vitamina_c_mg: 14, vitamina_d_ug: 0 },
  { nombre: 'Jitomate (tomate bola)', categoria: 'Verduras', porcion_tipica_g: 120, porcion_label: '1 jitomate',
    calorias: 20, proteina_g: 1, carbohidratos_g: 4.3, grasas_g: 0.2, grasas_saturadas_g: 0,
    fibra_g: 1.5, sodio_mg: 11, azucar_g: 2.8, colesterol_mg: 0, calcio_mg: 12, hierro_mg: 0.4, vitamina_c_mg: 19, vitamina_d_ug: 0 },
  { nombre: 'Cebolla blanca cruda', categoria: 'Verduras', porcion_tipica_g: 110, porcion_label: '1 cebolla',
    calorias: 40, proteina_g: 1.1, carbohidratos_g: 9.3, grasas_g: 0.1, grasas_saturadas_g: 0,
    fibra_g: 1.7, sodio_mg: 4, azucar_g: 4.2, colesterol_mg: 0, calcio_mg: 23, hierro_mg: 0.2, vitamina_c_mg: 7.4, vitamina_d_ug: 0 },
  { nombre: 'Ajo', categoria: 'Verduras', porcion_tipica_g: 3, porcion_label: '1 diente',
    calorias: 149, proteina_g: 6.4, carbohidratos_g: 33, grasas_g: 0.5, grasas_saturadas_g: 0.1,
    fibra_g: 2.1, sodio_mg: 17, azucar_g: 1, colesterol_mg: 0, calcio_mg: 181, hierro_mg: 1.7, vitamina_c_mg: 31, vitamina_d_ug: 0 },
  { nombre: 'Papa cocida con cáscara', categoria: 'Verduras', porcion_tipica_g: 150, porcion_label: '1 papa mediana',
    calorias: 87, proteina_g: 1.9, carbohidratos_g: 20, grasas_g: 0.1, grasas_saturadas_g: 0,
    fibra_g: 1.8, sodio_mg: 5, azucar_g: 0.9, colesterol_mg: 0, calcio_mg: 5, hierro_mg: 0.3, vitamina_c_mg: 8, vitamina_d_ug: 0 },
  { nombre: 'Camote cocido', categoria: 'Verduras', porcion_tipica_g: 130, porcion_label: '1 camote mediano',
    calorias: 90, proteina_g: 2, carbohidratos_g: 21, grasas_g: 0.1, grasas_saturadas_g: 0,
    fibra_g: 3.3, sodio_mg: 36, azucar_g: 6.5, colesterol_mg: 0, calcio_mg: 38, hierro_mg: 0.7, vitamina_c_mg: 20, vitamina_d_ug: 0 },
  { nombre: 'Calabacita cruda', categoria: 'Verduras', porcion_tipica_g: 120, porcion_label: '1 calabacita',
    calorias: 17, proteina_g: 1.2, carbohidratos_g: 3.1, grasas_g: 0.3, grasas_saturadas_g: 0.1,
    fibra_g: 1, sodio_mg: 8, azucar_g: 2.5, colesterol_mg: 0, calcio_mg: 16, hierro_mg: 0.4, vitamina_c_mg: 17, vitamina_d_ug: 0 },
  { nombre: 'Chile poblano', categoria: 'Verduras', porcion_tipica_g: 95, porcion_label: '1 chile',
    calorias: 27, proteina_g: 1.3, carbohidratos_g: 6.7, grasas_g: 0.1, grasas_saturadas_g: 0,
    fibra_g: 2, sodio_mg: 3, azucar_g: 3.7, colesterol_mg: 0, calcio_mg: 11, hierro_mg: 0.5, vitamina_c_mg: 73, vitamina_d_ug: 0 },
  { nombre: 'Nopal cocido', categoria: 'Verduras', porcion_tipica_g: 86, porcion_label: '1 taza',
    calorias: 22, proteina_g: 1.5, carbohidratos_g: 4.8, grasas_g: 0.1, grasas_saturadas_g: 0,
    fibra_g: 2, sodio_mg: 19, azucar_g: 1.1, colesterol_mg: 0, calcio_mg: 141, hierro_mg: 0.5, vitamina_c_mg: 6.3, vitamina_d_ug: 0 },
  { nombre: 'Lechuga romana', categoria: 'Verduras', porcion_tipica_g: 47, porcion_label: '1 taza',
    calorias: 17, proteina_g: 1.2, carbohidratos_g: 3.3, grasas_g: 0.3, grasas_saturadas_g: 0,
    fibra_g: 2.1, sodio_mg: 8, azucar_g: 1.2, colesterol_mg: 0, calcio_mg: 33, hierro_mg: 0.9, vitamina_c_mg: 4, vitamina_d_ug: 0 },
  { nombre: 'Pepino crudo', categoria: 'Verduras', porcion_tipica_g: 150, porcion_label: '½ pepino',
    calorias: 15, proteina_g: 0.7, carbohidratos_g: 3.6, grasas_g: 0.1, grasas_saturadas_g: 0,
    fibra_g: 0.5, sodio_mg: 2, azucar_g: 1.7, colesterol_mg: 0, calcio_mg: 16, hierro_mg: 0.3, vitamina_c_mg: 2.8, vitamina_d_ug: 0 },
  { nombre: 'Chayote cocido', categoria: 'Verduras', porcion_tipica_g: 200, porcion_label: '1 chayote',
    calorias: 25, proteina_g: 0.6, carbohidratos_g: 5.9, grasas_g: 0.3, grasas_saturadas_g: 0,
    fibra_g: 1.7, sodio_mg: 198, azucar_g: 2.2, colesterol_mg: 0, calcio_mg: 9, hierro_mg: 0.3, vitamina_c_mg: 7, vitamina_d_ug: 0 },
  { nombre: 'Betabel crudo', categoria: 'Verduras', porcion_tipica_g: 82, porcion_label: '1 betabel',
    calorias: 43, proteina_g: 1.6, carbohidratos_g: 10, grasas_g: 0.2, grasas_saturadas_g: 0,
    fibra_g: 2.8, sodio_mg: 78, azucar_g: 6.8, colesterol_mg: 0, calcio_mg: 16, hierro_mg: 0.8, vitamina_c_mg: 4.9, vitamina_d_ug: 0 },
  { nombre: 'Elote desgranado cocido', categoria: 'Verduras', porcion_tipica_g: 82, porcion_label: '½ taza',
    calorias: 96, proteina_g: 3.4, carbohidratos_g: 21, grasas_g: 1.5, grasas_saturadas_g: 0.2,
    fibra_g: 2.4, sodio_mg: 15, azucar_g: 4.5, colesterol_mg: 0, calcio_mg: 2, hierro_mg: 0.5, vitamina_c_mg: 6.8, vitamina_d_ug: 0 },
  { nombre: 'Ejotes cocidos', categoria: 'Verduras', porcion_tipica_g: 125, porcion_label: '1 taza',
    calorias: 35, proteina_g: 1.9, carbohidratos_g: 7.9, grasas_g: 0.3, grasas_saturadas_g: 0,
    fibra_g: 3.4, sodio_mg: 1, azucar_g: 3.3, colesterol_mg: 0, calcio_mg: 37, hierro_mg: 1, vitamina_c_mg: 12, vitamina_d_ug: 0 },

  // ─── Frutas ────────────────────────────────────────────────────────────────
  { nombre: 'Manzana roja', categoria: 'Frutas', porcion_tipica_g: 182, porcion_label: '1 manzana',
    calorias: 52, proteina_g: 0.3, carbohidratos_g: 14, grasas_g: 0.2, grasas_saturadas_g: 0,
    fibra_g: 2.4, sodio_mg: 1, azucar_g: 10, colesterol_mg: 0, calcio_mg: 6, hierro_mg: 0.1, vitamina_c_mg: 4.6, vitamina_d_ug: 0 },
  { nombre: 'Plátano / Banana', categoria: 'Frutas', porcion_tipica_g: 118, porcion_label: '1 plátano',
    calorias: 89, proteina_g: 1.1, carbohidratos_g: 23, grasas_g: 0.3, grasas_saturadas_g: 0.1,
    fibra_g: 2.6, sodio_mg: 1, azucar_g: 12, colesterol_mg: 0, calcio_mg: 5, hierro_mg: 0.3, vitamina_c_mg: 8.7, vitamina_d_ug: 0 },
  { nombre: 'Naranja', categoria: 'Frutas', porcion_tipica_g: 131, porcion_label: '1 naranja',
    calorias: 47, proteina_g: 0.9, carbohidratos_g: 12, grasas_g: 0.1, grasas_saturadas_g: 0,
    fibra_g: 2.4, sodio_mg: 0, azucar_g: 9.4, colesterol_mg: 0, calcio_mg: 40, hierro_mg: 0.1, vitamina_c_mg: 53, vitamina_d_ug: 0 },
  { nombre: 'Mango', categoria: 'Frutas', porcion_tipica_g: 165, porcion_label: '1 taza',
    calorias: 60, proteina_g: 0.8, carbohidratos_g: 15, grasas_g: 0.4, grasas_saturadas_g: 0.1,
    fibra_g: 1.6, sodio_mg: 1, azucar_g: 14, colesterol_mg: 0, calcio_mg: 11, hierro_mg: 0.2, vitamina_c_mg: 36, vitamina_d_ug: 0 },
  { nombre: 'Aguacate', categoria: 'Frutas', porcion_tipica_g: 75, porcion_label: '½ aguacate',
    calorias: 160, proteina_g: 2, carbohidratos_g: 9, grasas_g: 15, grasas_saturadas_g: 2.1,
    fibra_g: 6.7, sodio_mg: 7, azucar_g: 0.7, colesterol_mg: 0, calcio_mg: 12, hierro_mg: 0.6, vitamina_c_mg: 10, vitamina_d_ug: 0 },
  { nombre: 'Fresa', categoria: 'Frutas', porcion_tipica_g: 150, porcion_label: '1 taza', gramos_por_unidad: 12,
    calorias: 32, proteina_g: 0.7, carbohidratos_g: 7.7, grasas_g: 0.3, grasas_saturadas_g: 0,
    fibra_g: 2, sodio_mg: 1, azucar_g: 4.9, colesterol_mg: 0, calcio_mg: 16, hierro_mg: 0.4, vitamina_c_mg: 59, vitamina_d_ug: 0 },
  { nombre: 'Uva verde / roja', categoria: 'Frutas', porcion_tipica_g: 92, porcion_label: '1 taza', gramos_por_unidad: 5,
    calorias: 69, proteina_g: 0.7, carbohidratos_g: 18, grasas_g: 0.2, grasas_saturadas_g: 0,
    fibra_g: 0.9, sodio_mg: 2, azucar_g: 15, colesterol_mg: 0, calcio_mg: 10, hierro_mg: 0.4, vitamina_c_mg: 3.2, vitamina_d_ug: 0 },
  { nombre: 'Sandía', categoria: 'Frutas', porcion_tipica_g: 152, porcion_label: '1 taza',
    calorias: 30, proteina_g: 0.6, carbohidratos_g: 7.6, grasas_g: 0.2, grasas_saturadas_g: 0,
    fibra_g: 0.4, sodio_mg: 1, azucar_g: 6.2, colesterol_mg: 0, calcio_mg: 7, hierro_mg: 0.2, vitamina_c_mg: 8.1, vitamina_d_ug: 0 },
  { nombre: 'Melón cantaloupe', categoria: 'Frutas', porcion_tipica_g: 160, porcion_label: '1 taza',
    calorias: 34, proteina_g: 0.8, carbohidratos_g: 8.2, grasas_g: 0.2, grasas_saturadas_g: 0,
    fibra_g: 0.9, sodio_mg: 16, azucar_g: 7.9, colesterol_mg: 0, calcio_mg: 9, hierro_mg: 0.2, vitamina_c_mg: 36, vitamina_d_ug: 0 },
  { nombre: 'Papaya', categoria: 'Frutas', porcion_tipica_g: 140, porcion_label: '1 taza',
    calorias: 43, proteina_g: 0.5, carbohidratos_g: 11, grasas_g: 0.3, grasas_saturadas_g: 0.1,
    fibra_g: 1.7, sodio_mg: 8, azucar_g: 7.8, colesterol_mg: 0, calcio_mg: 20, hierro_mg: 0.3, vitamina_c_mg: 62, vitamina_d_ug: 0 },
  { nombre: 'Piña', categoria: 'Frutas', porcion_tipica_g: 165, porcion_label: '1 taza',
    calorias: 50, proteina_g: 0.5, carbohidratos_g: 13, grasas_g: 0.1, grasas_saturadas_g: 0,
    fibra_g: 1.4, sodio_mg: 1, azucar_g: 9.9, colesterol_mg: 0, calcio_mg: 13, hierro_mg: 0.3, vitamina_c_mg: 47, vitamina_d_ug: 0 },
  { nombre: 'Durazno / Melocotón', categoria: 'Frutas', porcion_tipica_g: 150, porcion_label: '1 durazno',
    calorias: 39, proteina_g: 0.9, carbohidratos_g: 10, grasas_g: 0.3, grasas_saturadas_g: 0,
    fibra_g: 1.5, sodio_mg: 0, azucar_g: 8.4, colesterol_mg: 0, calcio_mg: 6, hierro_mg: 0.3, vitamina_c_mg: 6.6, vitamina_d_ug: 0 },
  { nombre: 'Pera', categoria: 'Frutas', porcion_tipica_g: 166, porcion_label: '1 pera',
    calorias: 57, proteina_g: 0.4, carbohidratos_g: 15, grasas_g: 0.1, grasas_saturadas_g: 0,
    fibra_g: 3.1, sodio_mg: 1, azucar_g: 9.8, colesterol_mg: 0, calcio_mg: 9, hierro_mg: 0.2, vitamina_c_mg: 4.3, vitamina_d_ug: 0 },
  { nombre: 'Kiwi', categoria: 'Frutas', porcion_tipica_g: 76, porcion_label: '1 kiwi',
    calorias: 61, proteina_g: 1.1, carbohidratos_g: 15, grasas_g: 0.5, grasas_saturadas_g: 0,
    fibra_g: 3, sodio_mg: 3, azucar_g: 9, colesterol_mg: 0, calcio_mg: 34, hierro_mg: 0.3, vitamina_c_mg: 93, vitamina_d_ug: 0 },
  { nombre: 'Mandarina', categoria: 'Frutas', porcion_tipica_g: 88, porcion_label: '1 mandarina',
    calorias: 53, proteina_g: 0.8, carbohidratos_g: 13, grasas_g: 0.3, grasas_saturadas_g: 0,
    fibra_g: 1.8, sodio_mg: 2, azucar_g: 11, colesterol_mg: 0, calcio_mg: 37, hierro_mg: 0.2, vitamina_c_mg: 27, vitamina_d_ug: 0 },
  { nombre: 'Limón', categoria: 'Frutas', porcion_tipica_g: 58, porcion_label: '1 limón',
    calorias: 29, proteina_g: 1.1, carbohidratos_g: 9.3, grasas_g: 0.3, grasas_saturadas_g: 0,
    fibra_g: 2.8, sodio_mg: 2, azucar_g: 2.5, colesterol_mg: 0, calcio_mg: 26, hierro_mg: 0.6, vitamina_c_mg: 53, vitamina_d_ug: 0 },
  { nombre: 'Guayaba', categoria: 'Frutas', porcion_tipica_g: 90, porcion_label: '1 guayaba',
    calorias: 68, proteina_g: 2.6, carbohidratos_g: 14, grasas_g: 1, grasas_saturadas_g: 0.3,
    fibra_g: 5.4, sodio_mg: 2, azucar_g: 8.9, colesterol_mg: 0, calcio_mg: 18, hierro_mg: 0.3, vitamina_c_mg: 228, vitamina_d_ug: 0 },
  { nombre: 'Ciruela', categoria: 'Frutas', porcion_tipica_g: 66, porcion_label: '1 ciruela',
    calorias: 46, proteina_g: 0.7, carbohidratos_g: 11, grasas_g: 0.3, grasas_saturadas_g: 0,
    fibra_g: 1.4, sodio_mg: 0, azucar_g: 9.9, colesterol_mg: 0, calcio_mg: 6, hierro_mg: 0.2, vitamina_c_mg: 9.5, vitamina_d_ug: 0 },
  { nombre: 'Coco rallado (natural)', categoria: 'Frutas', porcion_tipica_g: 25, porcion_label: '¼ taza',
    calorias: 354, proteina_g: 3.3, carbohidratos_g: 15, grasas_g: 33, grasas_saturadas_g: 30,
    fibra_g: 9, sodio_mg: 20, azucar_g: 6.2, colesterol_mg: 0, calcio_mg: 14, hierro_mg: 2.4, vitamina_c_mg: 3.3, vitamina_d_ug: 0 },

  // ─── Grasas, aceites y semillas ────────────────────────────────────────────
  { nombre: 'Aceite de oliva', categoria: 'Aceites y grasas', porcion_tipica_g: 14, porcion_label: '1 cda',
    calorias: 884, proteina_g: 0, carbohidratos_g: 0, grasas_g: 100, grasas_saturadas_g: 14,
    fibra_g: 0, sodio_mg: 2, azucar_g: 0, colesterol_mg: 0, calcio_mg: 1, hierro_mg: 0.6, vitamina_c_mg: 0, vitamina_d_ug: 0 },
  { nombre: 'Aceite de coco', categoria: 'Aceites y grasas', porcion_tipica_g: 14, porcion_label: '1 cda',
    calorias: 862, proteina_g: 0, carbohidratos_g: 0, grasas_g: 100, grasas_saturadas_g: 87,
    fibra_g: 0, sodio_mg: 0, azucar_g: 0, colesterol_mg: 0, calcio_mg: 1, hierro_mg: 0.1, vitamina_c_mg: 0, vitamina_d_ug: 0 },
  { nombre: 'Aceite vegetal (girasol)', categoria: 'Aceites y grasas', porcion_tipica_g: 14, porcion_label: '1 cda',
    calorias: 884, proteina_g: 0, carbohidratos_g: 0, grasas_g: 100, grasas_saturadas_g: 10,
    fibra_g: 0, sodio_mg: 0, azucar_g: 0, colesterol_mg: 0, calcio_mg: 0, hierro_mg: 0, vitamina_c_mg: 0, vitamina_d_ug: 0 },
  { nombre: 'Aguacate (pasta/guacamole base)', categoria: 'Aceites y grasas', porcion_tipica_g: 75, porcion_label: '½ aguacate',
    calorias: 160, proteina_g: 2, carbohidratos_g: 9, grasas_g: 15, grasas_saturadas_g: 2.1,
    fibra_g: 6.7, sodio_mg: 7, azucar_g: 0.7, colesterol_mg: 0, calcio_mg: 12, hierro_mg: 0.6, vitamina_c_mg: 10, vitamina_d_ug: 0 },
  { nombre: 'Almendras', categoria: 'Nueces y semillas', porcion_tipica_g: 28, porcion_label: '1 puñado (≈23 piezas)',
    calorias: 579, proteina_g: 21, carbohidratos_g: 22, grasas_g: 50, grasas_saturadas_g: 3.8,
    fibra_g: 12.5, sodio_mg: 1, azucar_g: 4.4, colesterol_mg: 0, calcio_mg: 264, hierro_mg: 3.7, vitamina_c_mg: 0, vitamina_d_ug: 0 },
  { nombre: 'Nuez de castilla', categoria: 'Nueces y semillas', porcion_tipica_g: 28, porcion_label: '1 puñado (≈14 mitades)',
    calorias: 654, proteina_g: 15, carbohidratos_g: 14, grasas_g: 65, grasas_saturadas_g: 6.1,
    fibra_g: 6.7, sodio_mg: 2, azucar_g: 2.6, colesterol_mg: 0, calcio_mg: 98, hierro_mg: 2.9, vitamina_c_mg: 1.3, vitamina_d_ug: 0 },
  { nombre: 'Cacahuate tostado', categoria: 'Nueces y semillas', porcion_tipica_g: 28, porcion_label: '1 puñado',
    calorias: 585, proteina_g: 24, carbohidratos_g: 21, grasas_g: 50, grasas_saturadas_g: 6.9,
    fibra_g: 8.5, sodio_mg: 18, azucar_g: 3.1, colesterol_mg: 0, calcio_mg: 54, hierro_mg: 1.6, vitamina_c_mg: 0, vitamina_d_ug: 0 },
  { nombre: 'Semillas de chía', categoria: 'Nueces y semillas', porcion_tipica_g: 12, porcion_label: '1 cda',
    calorias: 486, proteina_g: 17, carbohidratos_g: 42, grasas_g: 31, grasas_saturadas_g: 3.3,
    fibra_g: 34, sodio_mg: 16, azucar_g: 0, colesterol_mg: 0, calcio_mg: 631, hierro_mg: 7.7, vitamina_c_mg: 1.6, vitamina_d_ug: 0 },
  { nombre: 'Semillas de girasol', categoria: 'Nueces y semillas', porcion_tipica_g: 28, porcion_label: '1 puñado',
    calorias: 584, proteina_g: 21, carbohidratos_g: 20, grasas_g: 51, grasas_saturadas_g: 4.5,
    fibra_g: 8.6, sodio_mg: 9, azucar_g: 2.6, colesterol_mg: 0, calcio_mg: 78, hierro_mg: 5.3, vitamina_c_mg: 1.4, vitamina_d_ug: 0 },
  { nombre: 'Crema de cacahuate (natural)', categoria: 'Nueces y semillas', porcion_tipica_g: 32, porcion_label: '2 cdas',
    calorias: 598, proteina_g: 25, carbohidratos_g: 20, grasas_g: 51, grasas_saturadas_g: 10,
    fibra_g: 6, sodio_mg: 17, azucar_g: 9.2, colesterol_mg: 0, calcio_mg: 49, hierro_mg: 1.9, vitamina_c_mg: 0, vitamina_d_ug: 0 },

  // ─── Tubérculos y raíces ───────────────────────────────────────────────────
  { nombre: 'Yuca cocida', categoria: 'Tubérculos', porcion_tipica_g: 78, porcion_label: '1 taza',
    calorias: 155, proteina_g: 1.2, carbohidratos_g: 38, grasas_g: 0.3, grasas_saturadas_g: 0.1,
    fibra_g: 1.8, sodio_mg: 14, azucar_g: 1.7, colesterol_mg: 0, calcio_mg: 16, hierro_mg: 0.3, vitamina_c_mg: 20, vitamina_d_ug: 0 },
  { nombre: 'Malanga cocida', categoria: 'Tubérculos', porcion_tipica_g: 78, porcion_label: '1 taza',
    calorias: 142, proteina_g: 0.5, carbohidratos_g: 34, grasas_g: 0.2, grasas_saturadas_g: 0,
    fibra_g: 4.1, sodio_mg: 11, azucar_g: 0.5, colesterol_mg: 0, calcio_mg: 18, hierro_mg: 0.6, vitamina_c_mg: 4.5, vitamina_d_ug: 0 },

  // ─── Suplementos y proteína ────────────────────────────────────────────────
  { nombre: 'Proteína whey en polvo', categoria: 'Suplementos', porcion_tipica_g: 30, porcion_label: '1 scoop',
    calorias: 375, proteina_g: 78, carbohidratos_g: 9, grasas_g: 5, grasas_saturadas_g: 2,
    fibra_g: 0, sodio_mg: 220, azucar_g: 4, colesterol_mg: 30, calcio_mg: 600, hierro_mg: 0.5, vitamina_c_mg: 0, vitamina_d_ug: 0 },
  { nombre: 'Proteína vegana en polvo', categoria: 'Suplementos', porcion_tipica_g: 30, porcion_label: '1 scoop',
    calorias: 350, proteina_g: 72, carbohidratos_g: 12, grasas_g: 4, grasas_saturadas_g: 0.5,
    fibra_g: 4, sodio_mg: 300, azucar_g: 2, colesterol_mg: 0, calcio_mg: 100, hierro_mg: 8, vitamina_c_mg: 0, vitamina_d_ug: 0 },
]

/**
 * Busca alimentos por nombre ignorando acentos y mayúsculas.
 */
export function buscarAlimentosComunes(query: string): AlimentoComun[] {
  if (!query.trim()) return []
  const normalizar = (s: string) =>
    s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '')
  const q = normalizar(query)
  return ALIMENTOS_COMUNES.filter((a) => normalizar(a.nombre).includes(q)).slice(0, 8)
}
